apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: all-peers-template
metadata:
  name: all-peers-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: peer0bank1dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: peer0bank1
      spec:
        volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
        containers:
          - name: peer0-bank1-banksco-com
            image: hyperledger/fabric-peer:2.2.0
            imagePullPolicy: Always
            command: ["sh","-c","peer node start"]
            env:
              - name: CORE_PEER_GOSSIP_ORGLEADER
                value: "false"
              - name: CORE_PEER_GOSSIP_USELEADERELECTION
                value: "true"
              - name: CORE_PEER_PROFILE_ENABLED
                value: "true"
              - name: CORE_PEER_TLS_ENABLED
                value: "true"
              - name: FABRIC_LOGGING_SPEC
                value: "DEBUG"
              - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/peer0.bank1.banksco.com/msp"
              - name: CORE_PEER_TLS_CERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/peer0.bank1.banksco.com/tls/server.crt"
              - name: CORE_PEER_TLS_KEY_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/peer0.bank1.banksco.com/tls/server.key"
              - name: CORE_PEER_TLS_ROOTCERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/peer0.bank1.banksco.com/tls/ca.crt"
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
            ports:
              - containerPort: 7051
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: peer0bank1-svc
  spec:
    ports:
    - name: "7051"
      port: 7051
      targetPort: 7051
    selector:
      name: peer0bank1

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: peer1bank1dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: peer1bank1
      spec:
        volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
        containers:
          - name: peer1-bank1-banksco-com
            image: hyperledger/fabric-peer:2.2.0
            imagePullPolicy: Always
            command: ["sh","-c","peer node start"]
            env:
              - name: CORE_PEER_GOSSIP_ORGLEADER
                value: "false"
              - name: CORE_PEER_GOSSIP_USELEADERELECTION
                value: "true"
              - name: CORE_PEER_PROFILE_ENABLED
                value: "true"
              - name: CORE_PEER_TLS_ENABLED
                value: "true"
              - name: FABRIC_LOGGING_SPEC
                value: "DEBUG"
              - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/peer1.bank1.banksco.com/msp"
              - name: CORE_PEER_TLS_CERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/peer1.bank1.banksco.com/tls/server.crt"
              - name: CORE_PEER_TLS_KEY_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/peer1.bank1.banksco.com/tls/server.key"
              - name: CORE_PEER_TLS_ROOTCERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/peer1.bank1.banksco.com/tls/ca.crt"
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
            ports:
              - containerPort: 7051
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: peer1bank1-svc
  spec:
    ports:
    - name: "7051"
      port: 7051
      targetPort: 7051
    selector:
      name: peer1bank1

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: peer0bank2dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: peer0bank2
      spec:
        volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
        containers:
          - name: peer0-bank2-banksco-com
            image: hyperledger/fabric-peer:2.2.0
            imagePullPolicy: Always
            command: ["sh","-c","peer node start"]
            env:
              - name: CORE_PEER_GOSSIP_ORGLEADER
                value: "false"
              - name: CORE_PEER_GOSSIP_USELEADERELECTION
                value: "true"
              - name: CORE_PEER_PROFILE_ENABLED
                value: "true"
              - name: CORE_PEER_TLS_ENABLED
                value: "true"
              - name: FABRIC_LOGGING_SPEC
                value: "DEBUG"
              - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
                value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer0.bank2.banksco.com/msp"
              - name: CORE_PEER_TLS_CERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer0.bank2.banksco.com/tls/server.crt"
              - name: CORE_PEER_TLS_KEY_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer0.bank2.banksco.com/tls/server.key"
              - name: CORE_PEER_TLS_ROOTCERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer0.bank2.banksco.com/tls/ca.crt"
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
            ports:
              - containerPort: 7051
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: peer0bank2-svc
  spec:
    ports:
    - name: "7051"
      port: 7051
      targetPort: 7051
    selector:
      name: peer0bank2

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: peer1bank2dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: peer1bank2
      spec:
        volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
        containers:
          - name: peer1-bank2-banksco-com
            image: hyperledger/fabric-peer:2.2.0
            imagePullPolicy: Always
            command: ["sh","-c","peer node start"]
            env:
              - name: CORE_PEER_GOSSIP_ORGLEADER
                value: "false"
              - name: CORE_PEER_GOSSIP_USELEADERELECTION
                value: "true"
              - name: CORE_PEER_PROFILE_ENABLED
                value: "true"
              - name: CORE_PEER_TLS_ENABLED
                value: "true"
              - name: FABRIC_LOGGING_SPEC
                value: "DEBUG"
              - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
                value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer1.bank2.banksco.com/msp"
              - name: CORE_PEER_TLS_CERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer1.bank2.banksco.com/tls/server.crt"
              - name: CORE_PEER_TLS_KEY_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer1.bank2.banksco.com/tls/server.key"
              - name: CORE_PEER_TLS_ROOTCERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer1.bank2.banksco.com/tls/ca.crt"
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
            ports:
              - containerPort: 7051

- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: peer1-bank2-svc
  spec:
    ports:
    - name: "7051"
      port: 7051
      targetPort: 7051
    selector:
      name: peer1bank2