apiVersion: v1
kind: DeploymentConfig
metadata:
  name: bbox
spec:
  replicas: 1
  selector:
    app: bbox
  template:
    metadata:
      labels:
        app: bbox
    spec:
      volumes: 
      - name: bbox-storage
        persistentVolumeClaim: 
          claimName: nfs-pvc1
          readonly: true
      containers:
      - name: bbox
        image: image-registry.openshift-image-registry.svc:5000/default/bbox:latest
        resources:
          limits:
            cpu: 1
            memory: 3Gi
        ports:
        - name: web
          port: 8080
          containerPort: 8080
        selector: 
          name: bbox
        volumeMounts:
        - mountPath: /data
          name: bbox-storage
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - bbox
      from:
        kind: ImageStreamTag
        namespace: michelmorat-fr
        name: 'bbox:latest'
    type: ImageChange
  strategy:
    type: Rolling