apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: fabric-secret-template
metadata:
  name: tpl-fabric-secret
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: fabric-secret-dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: fabric-secret
      spec:
        volumes:
        - name: fabricsecretfiles
          persistentVolumeClaim:
            claimName: fabric-secret-pvc
        initContainers:
        - name: app-init
          image: image-registry.openshift-image-registry.svc:5000/${PROJECT}/fabric-secret-alpine:latest
          volumeMounts:
          - mountPath: /fabric-secret
            name: fabricsecretfiles
          selector:
            name: fabric-secret
        containers:
          - name: fabrictools
            image: hyperledger/fabric-tools:2.2.0
            imagePullPolicy: Always
            command: ["sh", "-c","cd /fabric-secret &&  chmod +x /fabric-secret/commands.sh && /fabric-secret/commands.sh"]
            env:
            - name: FABRIC_CFG_PATH
              value: "/fabric-secret"
            volumeMounts:
              - mountPath: /fabric-secret
                name: fabricsecretfiles
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: fabric-secret-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_SIZE}
    storageClassName: ${STORAGE_CLASS}     
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fabric-secret-alpine
  spec:
    lookupPolicy:
      local: false
    tags:
      - name: latest
        annotations: null
        from:
          kind: DockerImage
          name: 'us.icr.io/${NAMESPACE}/fabric-secret-alpine:latest'
        generation: 2
        importPolicy: {}
        referencePolicy:
          type: Local
parameters:
- description: Value for project
  displayName: project
  name: PROJECT
  required: true
- description: storage size
  displayName: storage size
  name: VOLUME_SIZE
  required: true
- description: storage Class Name
  displayName: storage Class Name
  name: STORAGE_CLASS
  required: true
- description: namespace
  displayName: NameSpace
  name: NAMESPACE
  required: true
