apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: fabric-get-secret-template
metadata:
  name: tpl-fabric-get-secret
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: fabric-get-secret-dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: fabric
      spec:
        volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
        containers:
          - resources: {}
            name: fabric-get-secret
            image: image-registry.openshift-image-registry.svc:5000/${PROJECT}/fabric-get-secret-ubuntu:latest
            command: ["/bin/sh"]
            args: ["-c", "while true; do echo hello; sleep 10;done"]
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
parameters:
- description: Value for project
  displayName: project
  name: PROJECT
  required: true
