apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amar-mongodb-pvc-yml-1
  namespace: adrienmarchal-iscfrance-fr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
