apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1 
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /data
    server: 172.30.126.120 
  persistentVolumeReclaimPolicy: Retain