kind: Pod
apiVersion: v1
metadata:
  name: nfs-server-pod
  labels:
    role: nfs
spec:
  volumes:
    - name: nfs-data
      emptyDir: {}
  containers:
    - name: nfs-server-container
      image: us.icr.io/bouygues-bloc-1600085663464/michelmorat-fr/nfs-server
      securityContext:
        privileged: true
      volumeMounts:
        - name: nfs-data
          mountPath: /data