apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose-cli.yaml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: orderer.banksco.com
  name: orderer.banksco.com
spec:
  replicas: 1
  selector:
    io.kompose.service: orderer.banksco.com
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: orderer.banksco.com
    spec:
      containers:
      - args:
        - orderer
        env:
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/orderer.genesis.block
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        image: ' '
        name: orderer.banksco.com
        ports:
        - containerPort: 7050
        resources: {}
        volumeMounts:
        - mountPath: /var/hyperledger/orderer/orderer.genesis.block
          name: orderer.banksco.com-claim0
        - mountPath: /var/hyperledger/orderer/msp
          name: orderer.banksco.com-claim1
        - mountPath: /var/hyperledger/orderer/tls
          name: orderer.banksco.com-claim2
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      hostname: orderer
      restartPolicy: Always
      volumes:
      - name: orderer.banksco.com-claim0
        persistentVolumeClaim:
          claimName: orderer.banksco.com-claim0
      - name: orderer.banksco.com-claim1
        persistentVolumeClaim:
          claimName: orderer.banksco.com-claim1
      - name: orderer.banksco.com-claim2
        persistentVolumeClaim:
          claimName: orderer.banksco.com-claim2
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - orderer.banksco.com
      from:
        kind: ImageStreamTag
        name: orderer.banksco.com:2.2.0
    type: ImageChange
status: {}
