apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: peer-template
metadata:
  name: peer-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: fabricpeerdc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: peer
      spec:
        volumes:
          - name: fabricfiles
            persistentVolumeClaim:
            claimName: fabric-pvc
        containers:
          - name: peer-banksco-com
            image: image-registry.openshift-image-registry.svc:5000/${PROJECT}/fabric-peer:latest
            imagePullPolicy: Always
            command: ["sh","-c","peer node start"]
            env:
              - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
                value: "exchangeNtw"
              - name: FABRIC_LOGGING_SPEC
                value: "INFO"
              - name: CORE_PEER_TLS_ENABLED
                value: "true"
              - name: CORE_PEER_GOSSIP_USELEADERELECTION
                value: "true"
              - name: CORE_PEER_GOSSIP_ORGLEADER
                value: "false"
              - name: CORE_PEER_PROFILE_ENABLED
                value: "true"
              - name: CORE_PEER_TLS_CERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/${PEER_BANKSCO_COM}/tls/server.crt"
              - name: CORE_PEER_TLS_KEY_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/${PEER_BANKSCO_COM}/tls/server.key"
              - name: CORE_PEER_TLS_ROOTCERT_FILE
                value: "/fabric/crypto-config/peerOrganizations/bank1.banksco.com/peers/${PEER_BANKSCO_COM}/tls/ca.crt"
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
            ports:
              - containerPort: 7051
                protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: peer-svc
  spec:
    ports:
    - name: peer
      port: 7051
      protocol: TCP
      targetPort: 7051
    selector:
      name: peer-banksco-com
parameters:
- description: Value for project
  displayName: project
  name: PROJECT
  required: true
- description: peer to create 
  displayName: peer name
  name: PEER_BANKSCO_COM
  required: true
