apiVersion: v1
kind: DeploymentConfig
metadata:
  name: bttest2
spec:
  replicas: 1
  selector:
    app: bttest2
  template:
    metadata:
      labels:
        app: bttest2
    spec:
      volumes: 
      - name: bttest2-storage
        persistentVolumeClaim: 
          claimName: bttest2-storage
      containers:
      - name: bttest2
        image: image-registry.openshift-image-registry.svc:5000/default/bttest2:latest
        resources:
          limits:
            cpu: 1
            memory: 3Gi
        ports:
        - name: web
          port: 8080
          containerPort: 8080
        selector: 
          name: bttest2
        volumeMounts:
        - mountPath: /pvc-data
          name: bttest2-storage
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - bttest2
      from:
        kind: ImageStreamTag
        namespace: default
        name: 'bttest2:latest'
    type: ImageChange
  strategy:
    type: Rolling