apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: fabric-template
metadata:
  name: tpl-orderer
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: fabricdc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: fabric
      spec:
        volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
        containers:
          - name: orderer-banksco-com
            image: hyperledger/fabric-orderer:2.2.0
            imagePullPolicy: Always
            command: ["sh", "-c","orderer"]
            env:
            - name: FABRIC_LOGGING_SPEC
              value: "info"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: "file"
            - name: ORDERER_GENERAL_GENESISFILE
              value: "/fabric/channel-artifacts/genesis.block"
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "OrdererMSP"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/msp"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/server.key"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/server.crt"
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/ca.crt"
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
            ports:
              - containerPort: 7050
                protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: orderer-svc
  spec:
    ports:
    - name: orderer
      port: 7050
      protocol: TCP
      targetPort: 7050
    selector:
      name: orderer-banksco-com


