apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: chaincode-template
metadata:
  name: tpl-chaincode
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: exchangecc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: exchangecc
      spec:
        containers:
          - name: exchangecc
            image: image-registry.openshift-image-registry.svc:5000/choroukamahri/exchangecc:latest
            imagePullPolicy: Always            
            env:
              - name: CHAINCODE_ID
                value: "exchangecc:85433bd624c03d1331f9ea8702ea3405fb487796ceb982f6b95b4844ca3a2057"
              - name: CHAINCODE_SERVER_ADDRESS
                value: "0.0.0.0:9999"       
            ports:
              - containerPort: 9999              


- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: exchangecc
  spec:
    ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
    selector:
      name: exchangecc

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: exchangecc2
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: exchangecc2
      spec:
        containers:
          - name: exchangecc2
            image: image-registry.openshift-image-registry.svc:5000/choroukamahri/exchangecc:latest
            imagePullPolicy: Always            
            env:
              - name: CHAINCODE_ID
                value: "exchangecc:16dd9632e6492b75655e328a9cf4fcb6e62a4cee3be4ae4fa909f5318cb432ea"
              - name: CHAINCODE_SERVER_ADDRESS
                value: "0.0.0.0:9999"       
            ports:
              - containerPort: 9999              


- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: exchangecc2
  spec:
    ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
    selector:
      name: exchangecc2