apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: fabric-template
metadata:
  name: tpl-orderer
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: fabric-orderer-dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    selector:
      name: orderer
    template:
      metadata:
        labels:
          name: orderer
      spec:
        selector:
          name: orderer
        volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
        - name: ordererfile
          persistentVolumeClaim:
            claimName: orderer-pvc
        containers:
          - name: orderer
            image: hyperledger/fabric-orderer:2.2.0
            imagePullPolicy: Always
            command: ["sh", "-c","orderer"]
            env:
            - name: FABRIC_LOGGING_SPEC
              value: "DEBUG"        
            - name: ORDERER_GENERAL_GENESISFILE
              value: "/fabric/channel-artifacts/genesis.block"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: "file"             
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "OrdererMSP"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/msp"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/server.key"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/server.crt"
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/ca.crt"
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
              - mountPath: /var/hyperledger/production/orderer
                name: ordererfile
            ports:
              - containerPort: 7050
                protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: orderer
  spec:
    ports:
    - name: orderer
      port: 7050
      protocol: TCP
      targetPort: 7050
    selector:
      name: orderer


- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: orderer-pvc
  spec:
    accessModes:
      - ReadWriteOnly
    resources:
      requests:
        storage: 1Gi
    storageClassName: ibmc-block-gold 
