apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: fabric-template
metadata:
  name: tpl-clibank
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: fabric-clibank${NUM}-dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: fabric
      spec:
        volumes:
          - name: fabricfiles
            persistentVolumeClaim:
              claimName: fabric-pvc
        containers:
          - name: clibank1
            image: hyperledger/fabric-tools:2.2.0
            imagePullPolicy: Always
            command: ["sh", "-c","sleep 24h"]
            env:
            - name: GOPATH
              value: "/opt/gopath"
            - name: CORE_VM_ENDPOINT
              value: "unix:///host/var/run/docker.sock"
            - name: FABRIC_LOGGING_SPEC
              value: "INFO"
            - name: CORE_PEER_ID
              value: "cliBank${NUM}"
            - name: CORE_PEER_ADDRESS
              value: "peer0.Bank${NUM}.banksco.com:7051"
            - name: CORE_PEER_LOCALMSPID
              value: "Bank${NUM}MSP"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/fabric/crypto-config/peerOrganizations/Bank${NUM}.banksco.com/peers/peer0.Bank${NUM}.banksco.com/tls/server.crt"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/fabric/crypto-config/peerOrganizations/Bank${NUM}.banksco.com/peers/peer0.Bank${NUM}.banksco.com/tls/server.key"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/fabric/crypto-config/peerOrganizations/Bank${NUM}.banksco.com/peers/peer0.Bank${NUM}.banksco.com/tls/ca.crt"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/fabric/crypto-config/peerOrganizations/Bank${NUM}.banksco.com/users/Admin@Bank${NUM}.banksco.com/msp"
            - name: CHANNEL_NAME
              value: "bankscochannel"
            - name: ORDERER_TLS_CA
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/msp/tlscacerts/tlsca.banksco.com-cert.pem"
            - name: PEER0_BANK1_TLS_CA
              value: "/fabric/crypto-config/peerOrganizations/Bank${NUM}.banksco.com/peers/peer0.Bank${NUM}.banksco.com/tls/ca.crt"
            - name: PEER0_BANK1_PRADDR
              value: "peer0.Bank${NUM}.banksco.com:7051"
            - name: PEER1_BANK1_TLS_CA
              value: "/fabric/crypto-config/peerOrganizations/Bank${NUM}.banksco.com/peers/peer1.Bank${NUM}.banksco.com/tls/ca.crt"
            - name: PEER1_BANK1_PRADDR
              value: "peer1.Bank${NUM}.banksco.com:7051"           
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
            ports:
              - containerPort: 7052
                protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: clibank-svc
  spec:
    ports:
    - name: clibank
      port: 7052
      protocol: TCP
      targetPort: 7052
    selector:
      name: clibank-banksco-com
parameters:
- description: number of the clibank
  displayName: number of the clibank
  name: NUM
  required: true

