apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: chaincode-template
metadata:
  name: tpl-chaincode
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: exchangecc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: exchangecc
      spec:
        containers:
          - name: exchangecc
            image: image-registry.openshift-image-registry.svc:5000/choroukamahri/exchangecc:latest
            imagePullPolicy: Always    
            env:
              - name: CHAINCODE_ID
                value: "exchangecc:420a85e6fdd4abfac055197e4a142308694aa7135b41887a4272856bab3ab924"
              - name: CHAINCODE_SERVER_ADDRESS
                value: "0.0.0.0:9999"       
            ports:
              - containerPort: 9999              


- apiVersion: v1
  kind: Service
  metadata:
    name: exchangecc
  spec:
    ports:
    - name: "exchangecc"
      port: 9999
      targetPort: 9999
    selector:
      name: exchangecc

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: exchangecc2
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: exchangecc2
      spec:
        containers:
          - name: exchangecc2
            image: image-registry.openshift-image-registry.svc:5000/choroukamahri/exchangecc:latest
            imagePullPolicy: Always   
            env:
              - name: CHAINCODE_ID
                value: "exchangecc:cc01e67418062f9b5779d957b95ec6d36cbdb1afd0d1f3a5378728a0ecb6323b"
              - name: CHAINCODE_SERVER_ADDRESS
                value: "0.0.0.0:9999"       
            ports:
              - containerPort: 9999              


- apiVersion: v1
  kind: Service
  metadata:
    name: exchangecc2
  spec:
    ports:
    - name: "exchangecc"
      port: 9999
      targetPort: 9999
    selector:
      name: exchangecc2

