apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: fabric-template
metadata:
  name: tpl-orderer-secret
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: fabric-orderer-secret-dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    selector:
      name: orderer-secret
    template:
      metadata:
        labels:
          name: orderer-secret
      spec:
        selector:
          name: orderer-secret
        volumes:
          - name: fabricfiles
            persistentVolumeClaim:
              claimName: fabric-pvc
          - name: ordererfile
            persistentVolumeClaim:
              claimName: orderer-pvc
          - name: secret-volume
            secret:
              secretName: secret-blockchain-orderer-solution2
        containers:
          - name: orderer-secret
            image: hyperledger/fabric-orderer:2.2.0
            imagePullPolicy: Always
            command: ["sh", "-c","orderer"]
            env:
            - name: FABRIC_LOGGING_SPEC
              value: "DEBUG"        
            - name: ORDERER_GENERAL_GENESISFILE
              value: "/fabric/channel-artifacts/genesis.block"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: "file"             
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "OrdererMSP"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/msp"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/etc/secret-volume/ordererorg.orderers.ordererdomain.tls.serverkey"
              #value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/server.key"
              #NOTE : corresponding file location is "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/server.key"
              #valueFrom:
              #  secretKeyRef:
              #    name: secret-blockchain-orderer-solution2
              #    key: ordererorg.orderers.ordererdomain.tls.serverkey
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/server.crt"
              #Note : if needed (in the future), get "server.crt" from Secrets
              #valueFrom:
              #  secretKeyRef:
              #    name: secret-blockchain-orderer-solution2
              #    #corresponding file location : "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/server.crt"
              #    key: ordererorg.orderers.ordererdomain.tls.servercrt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/ca.crt"
              #Note : if needed (in the future), get "ca.crt" from Secrets
              #valueFrom:
              #  secretKeyRef:
              #    name: secret-blockchain-orderer-solution2
              #    #corresponding file location : "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/tls/ca.crt"
              #    key: ordererorg.orderers.ordererdomain.tls.cacrt
            volumeMounts:
              - name: fabricfiles
                mountPath: /fabric
              - name: ordererfile
                mountPath: /var/hyperledger/production/orderer
              - name: secret-volume
                mountPath: /etc/secret-volume
                readOnly: true
            ports:
              - containerPort: 7050
                protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: orderer
  spec:
    ports:
    - name: orderer
      port: 7050
      protocol: TCP
      targetPort: 7050
    selector:
      name: orderer


- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: orderer-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: ibmc-block-retain-bronze
