apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: fabric-template
metadata:
  name: tpl-clibank2
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: fabric-clibank2-dc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: clibank2
      spec:
        volumes:
          - name: fabricfiles
            persistentVolumeClaim:
              claimName: fabric-pvc
        containers:
          - name: clibank2
            image: hyperledger/fabric-tools:2.2.1
            imagePullPolicy: Always
            command: ["sh", "-c","cd ../fabric &&  chmod +x ../fabric/channelclibank2.sh && ../fabric/channelclibank2.sh && sleep 24h"]
            env:
            - name: GOPATH
              value: "/opt/gopath"
            - name: CORE_VM_ENDPOINT
              value: "unix:///host/var/run/docker.sock"
            - name: FABRIC_LOGGING_SPEC
              value: "DEBUG"
            - name: CORE_PEER_ID
              value: "cliBank2"
            - name: CORE_PEER_ADDRESS
              value: "peer2:7051"
            - name: CORE_PEER_LOCALMSPID
              value: "Bank2MSP"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer2.bank2.banksco.com/tls/server.crt"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer2.bank2.banksco.com/tls/server.key"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer2.bank2.banksco.com/tls/ca.crt"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/users/Admin@bank2.banksco.com/msp"
            - name: CHANNEL_NAME
              value: "bankscochannel"
            - name: ORDERER_TLS_CA
              value: "/fabric/crypto-config/ordererOrganizations/banksco.com/orderers/orderer.banksco.com/msp/tlscacerts/tlsca.banksco.com-cert.pem"
            - name: PEER2_BANK2_TLS_CA
              value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer2.bank2.banksco.com/tls/ca.crt"
            - name: PEER2_BANK2_PRADDR
              value: "peer2:7051"
            - name: PEER3_BANK2_TLS_CA
              value: "/fabric/crypto-config/peerOrganizations/bank2.banksco.com/peers/peer3.bank2.banksco.com/tls/ca.crt"
            - name: PEER3_BANK2_PRADDR
              value: "peer3:7051"           
            volumeMounts:
              - mountPath: /fabric
                name: fabricfiles
            ports:
              - containerPort: 7052
                protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: clibank2-svc
  spec:
    ports:
    - name: clibank
      port: 7052
      protocol: TCP
      targetPort: 7052
    selector:
      name: clibank2

