apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: chaincode-template
metadata:
  name: tpl-chaincode
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: exchangecc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: exchangecc
      spec:
        containers:
          - name: exchangecc
            image: image-registry.openshift-image-registry.svc:5000/choroukamahri/exchangecc:latest
            imagePullPolicy: Always            
            env:
              - name: CHAINCODE_ID
                value: "basic_1.0:16be29753715731c1ebd074832a9a99d14e3e93ed03e6a9c0a16f7e1d639f008"
              - name: CHAINCODE_SERVER_ADDRESS
                value: "0.0.0.0:9999"       
            ports:
              - containerPort: 9999              


- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    labels: null
    name: exchangecc
  spec:
    ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
    selector:
      name: exchangecc
   