apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: chaincode-template
metadata:
  name: tpl-chaincode
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: exchangecc
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: exchangecc
      spec:
        containers:
          - name: exchangecc
            image: image-registry.openshift-image-registry.svc:5000/choroukamahri/exchangecc:latest
            imagePullPolicy: Always    
            env:
              - name: CHAINCODE_ID
                value: "exchangecc:1843cb71d30a6e004b7f009297b928aaa668ab2a600981fc5b73f25434dd782b"
              - name: CHAINCODE_SERVER_ADDRESS
                value: "0.0.0.0:9999"       
            ports:
              - containerPort: 9999              


- apiVersion: v1
  kind: Service
  metadata:
    name: exchangecc
  spec:
    ports:
    - name: "exchangecc"
      port: 9999
      targetPort: 9999
    selector:
      name: exchangecc

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: exchangecc2
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          name: exchangecc2
      spec:
        containers:
          - name: exchangecc2
            image: image-registry.openshift-image-registry.svc:5000/choroukamahri/exchangecc:latest
            imagePullPolicy: Always   
            env:
              - name: CHAINCODE_ID
                value: "exchangecc:2b34d9001550eaaa078277408edeaab8ffd2fd3be85698f12c91933df7d57ac1"
              - name: CHAINCODE_SERVER_ADDRESS
                value: "0.0.0.0:9999"       
            ports:
              - containerPort: 9999              


- apiVersion: v1
  kind: Service
  metadata:
    name: exchangecc2
  spec:
    ports:
    - name: "exchangecc"
      port: 9999
      targetPort: 9999
    selector:
      name: exchangecc2

