apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose-cli.yaml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: peer0.bank2.banksco.com
  name: peer0.bank2.banksco.com
spec:
  ports:
  - name: "8051"
    port: 8051
    targetPort: 7051
  - name: "8053"
    port: 8053
    targetPort: 7053
  selector:
    io.kompose.service: peer0.bank2.banksco.com
status:
  loadBalancer: {}
