apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose-cli.yaml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: peer1.bank1.banksco.com
  name: peer1.bank1.banksco.com
spec:
  ports:
  - name: "7056"
    port: 7056
    targetPort: 7051
  - name: "7058"
    port: 7058
    targetPort: 7053
  selector:
    io.kompose.service: peer1.bank1.banksco.com
status:
  loadBalancer: {}
