# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

services:

  orderer0.banksco.com:
    container_name: orderer0.banksco.com
    image: hyperledger/fabric-orderer:2.2.0
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer0.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Orderer0MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer0.genesis.block
    - ../crypto-config/ordererOrganizations/banksco.com/orderers/orderer0.banksco.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/banksco.com/orderers/orderer0.banksco.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7040:7050

  orderer1.banksco.com:
    container_name: orderer1.banksco.com
    image: hyperledger/fabric-orderer:2.2.0
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer1.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer1.genesis.block
    - ../crypto-config/ordererOrganizations/banksco.com/orderers/orderer1.banksco.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/banksco.com/orderers/orderer1.banksco.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7041:7050
  
  orderer2.banksco.com:
    container_name: orderer2.banksco.com
    image: hyperledger/fabric-orderer:2.2.0
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer2.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Orderer2MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer2.genesis.block
    - ../crypto-config/ordererOrganizations/banksco.com/orderers/orderer2.banksco.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/banksco.com/orderers/orderer2.banksco.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7042:7050

  peer0.bank1.banksco.com:
    container_name: peer0.bank1.banksco.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank1.banksco.com
      - CORE_PEER_ADDRESS=peer0.bank1.banksco.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank1.banksco.com:7051
      - CORE_PEER_LOCALMSPID=Bank1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bank1.banksco.com/peers/peer0.bank1.banksco.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bank1.banksco.com/peers/peer0.bank1.banksco.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer0.bank2.banksco.com:
    container_name: peer0.bank2.banksco.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank2.banksco.com
      - CORE_PEER_ADDRESS=peer0.bank2.banksco.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank2.banksco.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank2.banksco.com:7051
      - CORE_PEER_LOCALMSPID=Bank2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bank2.banksco.com/peers/peer0.bank2.banksco.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bank2.banksco.com/peers/peer0.bank2.banksco.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053

  peer0.bank3.banksco.com:
    container_name: peer0.bank3.banksco.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank3.banksco.com
      - CORE_PEER_ADDRESS=peer0.bank3.banksco.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank3.banksco.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank3.banksco.com:7051
      - CORE_PEER_LOCALMSPID=Bank3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bank3.banksco.com/peers/peer0.bank3.banksco.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bank3.banksco.com/peers/peer0.bank3.banksco.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

